// ReagentCategory describes a product's broad form (for example, ANTIBODY or
// BUFFER). These tags describe the experimentally useful capability. Keep this
// vocabulary shared by reagent intake, inventory and technique-readiness.
export const reagentCapabilityTags = [
  "CELL_CULTURE_MEDIUM",
  "SERUM_SUPPLEMENT",
  "ANTIBIOTIC_SUPPLEMENT",
  "SELECTION_ANTIBIOTIC",
  "CELL_DISSOCIATION_REAGENT",
  "CELL_FREEZING_REAGENT",
  "CELL_COUNTING_REAGENT",
  "CELL_STAIN_REAGENT",
  "CELL_CULTURE_VESSEL",
  "SYRINGE_CONSUMABLE",
  "ANESTHETIC_REAGENT",
  "SOLVENT_REAGENT",
  "DISINFECTION_REAGENT",
  "MYCOPLASMA_TEST_REAGENT",
  "TRANSDUCTION_REAGENT",
  "GENE_DELIVERY_REAGENT",
  "CELL_STIMULATION_REAGENT",
  "SIGNALING_MODULATOR",
  "OSTEOCLAST_DIFFERENTIATION_REAGENT",
  "BONE_REMODELING_SIGNAL",
  "IMMUNE_CYTOKINE_REAGENT",
  "OSTEOGENIC_DIFFERENTIATION_REAGENT",
  "ECM_COATING_REAGENT",
  "STEM_CELL_MATRIX",
  "AUTOPHAGY_INDUCER",
  "AUTOPHAGY_FLUX_INHIBITOR",
  "EXOSOME_DEPLETED_SERUM",
  "EXOSOME_CAPTURE_REAGENT",
  "ECM_DEGRADATION_ASSAY_REAGENT",
  "ECM_REMODELING_MODULATOR",
  "MITOCHONDRIAL_STAIN",
  "MITOCHONDRIAL_MEMBRANE_POTENTIAL_DYE",
  "MITOCHONDRIAL_SUPEROXIDE_DYE",
  "MITOCHONDRIAL_RESPIRATION_ASSAY_REAGENT",
  "MITOCHONDRIAL_STRESSOR",
  "TYPE_I_INTERFERON_REAGENT",
  "TYPE_II_INTERFERON_REAGENT",
  "INTERFERON_PATHWAY_MODULATOR",
  "INNATE_IMMUNE_STIMULANT",
  "INFLAMMASOME_ACTIVATOR",
  "T_CELL_ACTIVATION_REAGENT",
  "T_CELL_LINEAGE_MARKER_REAGENT",
  "B_CELL_ACTIVATION_REAGENT",
  "B_CELL_LINEAGE_MARKER_REAGENT",
  "NK_CELL_ACTIVATION_REAGENT",
  "NK_CELL_MARKER_REAGENT",
  "MYELOID_POLARIZATION_REAGENT",
  "MYELOID_LINEAGE_MARKER_REAGENT",
  "IMMUNE_CHECKPOINT_REAGENT",
  "IMMUNE_METABOLISM_MODULATOR",
  "ANTIGEN_PRESENTATION_REAGENT",
  "COMPLEMENT_FC_EFFECTOR_REAGENT",
  "IMMUNE_CHEMOTAXIS_REAGENT",
  "FC_RECEPTOR_BLOCKING_REAGENT",
  "IMMUNE_CELL_ENRICHMENT_REAGENT",
  "WB_LYSIS_BUFFER",
  "WB_LOADING_BUFFER",
  "WB_BLOCKING_BUFFER",
  "WB_WASH_BUFFER",
  "WB_TRANSFER_REAGENT",
  "WB_TRANSFER_MEMBRANE",
  "WB_PRIMARY_ANTIBODY",
  "WB_PROTEIN_MARKER",
  "WB_DETECTION_SUBSTRATE",
  "WB_SECONDARY_ANTIBODY",
  "PROTEASE_INHIBITOR",
  "PHOSPHATASE_INHIBITOR",
  "PROTEIN_QUANTIFICATION_REAGENT",
  "REDUCING_AGENT",
  "GEL_STAIN",
  "DNA_EXTRACTION_REAGENT",
  "RNA_EXTRACTION_REAGENT",
  "PLASMID_PREP_REAGENT",
  "PCR_MASTER_MIX",
  "REVERSE_TRANSCRIPTION_REAGENT",
  "QPCR_MASTER_MIX",
  "NUCLEASE_FREE_WATER",
  "DNASE_REAGENT",
  "RNASE_INHIBITOR",
  "TRANSFECTION_REAGENT",
  "FIXATIVE",
  "PERMEABILIZATION_REAGENT",
  "BLOCKING_REAGENT",
  "IF_PRIMARY_ANTIBODY",
  "IF_FLUORESCENT_SECONDARY_ANTIBODY",
  "CHIP_GRADE_ANTIBODY",
  "PROTEIN_A_G_MAGNETIC_BEADS",
  "TRANSPOSASE_REAGENT",
  "NUCLEI_ISOLATION_REAGENT",
  "SINGLE_CELL_BARCODING_REAGENT",
  "OLIGO_BARCODED_ANTIBODY_PANEL",
  "SPATIAL_PROBE_PANEL",
  "CRISPR_GUIDE_LIBRARY",
  "TARGET_ENRICHMENT_PROBE",
  "BISULFITE_CONVERSION_REAGENT",
  "METABOLITE_EXTRACTION_REAGENT",
  "HOST_DNA_DEPLETION_REAGENT",
  "RRNA_DEPLETION_REAGENT",
  "PHOSPHOPEPTIDE_ENRICHMENT_REAGENT",
  "STABLE_ISOTOPE_TRACER",
  "NUCLEAR_STAIN",
  "CYTOSKELETON_STAIN",
  "ORGANELLE_STAIN",
  "MOUNTING_MEDIUM",
  "IF_WASH_BUFFER",
  "ELISA_COATING_REAGENT",
  "ELISA_BLOCKING_REAGENT",
  "ELISA_WASH_BUFFER",
  "ELISA_DETECTION_ANTIBODY",
  "ELISA_SUBSTRATE",
  "FLOW_PRIMARY_ANTIBODY",
  "FLOW_FLUORESCENT_ANTIBODY",
  "FLOW_STAIN_BUFFER",
  "FLOW_VIABILITY_DYE",
  "EXOSOME_ISOLATION_REAGENT",
  "DENSITY_GRADIENT_MEDIUM",
  "ERYTHROCYTE_LYSIS_BUFFER",
  "TISSUE_DISSOCIATION_ENZYME",
  "DNA_POLYMERASE",
  "PCR_PRIMER_SET",
  "DNTP_MIX",
  "DNA_LIGASE",
  "RESTRICTION_ENDONUCLEASE",
  "DNA_BINDING_MAGNETIC_BEADS",
  "QPCR_PROBE",
  "ELISA_CAPTURE_ANTIBODY",
  "ELISA_STANDARD",
  "ELISA_COMPLETE_KIT",
  "FLOW_ANTIBODY_PANEL",
  "ANTICOAGULANT_REAGENT",
  "SAMPLE_PRESERVATION_REAGENT",
  "HISTOLOGY_STAIN_REAGENT",
  "CELL_VIABILITY_ASSAY_REAGENT",
  "MICROBIAL_CULTURE_MEDIUM",
  "CALIBRATION_STANDARD",
  "INTERNAL_STANDARD",
  "LIBRARY_PREPARATION_REAGENT",
  "SEQUENCING_RUN_REAGENT",
  "INDEXING_PRIMER",
  "OMICS_LABELING_REAGENT",
  "ANALGESIC_REAGENT",
] as const;

// Kept as a compatibility export while callers move to the clearer capability
// terminology. Existing stored tags keep their stable codes.
export const experimentTags = reagentCapabilityTags;

export type ReagentCapabilityTag = (typeof reagentCapabilityTags)[number];
export type ExperimentTag = ReagentCapabilityTag;

const reagentCapabilityTagSet = new Set<string>(reagentCapabilityTags);

export function isReagentCapabilityTag(value: string): value is ReagentCapabilityTag {
  return reagentCapabilityTagSet.has(value);
}
export type RuleLevelValue = "MIN_REQUIRED" | "RECOMMENDED";
export type MatcherTypeValue =
  | "TAG_ANY"
  | "NAME_ANY"
  | "ANTIBODY_TARGET_ANY"
  | "PRIMER_TARGET_ANY"
  | "PRIMER_REFERENCE";

export type AntibodyRoleValue = "PRIMARY" | "SECONDARY";

export type RuleDefinition = {
  experimentCode: string;
  directionCode?: string;
  level: RuleLevelValue;
  displayNameZh: string;
  displayNameEn: string;
  matcherType: MatcherTypeValue;
  matcherValues: string[];
  matcherAntibodyRole?: AntibodyRoleValue;
  requiredKeywords?: string[];
};

export type ExperimentTypeDefinition = {
  code: string;
  nameZh: string;
  nameEn: string;
  aliases: string[];
  descriptionZh: string;
  descriptionEn: string;
  supportsManualResolution: boolean;
};

export const experimentTypeCatalog: readonly ExperimentTypeDefinition[] = [
  {
    code: "WB",
    nameZh: "Western Blot",
    nameEn: "Western Blot",
    aliases: ["WB", "Western blot", "Immunoblot", "免疫印迹", "蛋白印迹"],
    descriptionZh: "蛋白电泳转膜后用抗体和底物进行条带检测。",
    descriptionEn: "Protein immunoblotting workflow with primary/secondary antibodies and detection substrate.",
    supportsManualResolution: true,
  },
  {
    code: "QPCR",
    nameZh: "qPCR",
    nameEn: "qPCR",
    aliases: ["qPCR", "RT-qPCR", "Real-time PCR", "Quantitative PCR", "实时荧光定量 PCR"],
    descriptionZh: "以 RNA 提取、逆转录和荧光定量扩增为核心的基因表达检测。",
    descriptionEn: "Gene-expression quantification workflow using RNA extraction, reverse transcription and real-time PCR.",
    supportsManualResolution: true,
  },
  {
    code: "IF",
    nameZh: "免疫荧光",
    nameEn: "Immunofluorescence",
    aliases: ["IF", "Immunofluorescence", "Immunostaining", "免疫荧光", "荧光染色"],
    descriptionZh: "通过固定、透化、抗体染色和封片进行细胞或组织成像。",
    descriptionEn: "Cell or tissue imaging workflow using fixation, permeabilization, antibody staining and mounting.",
    supportsManualResolution: true,
  },
  {
    code: "ELISA",
    nameZh: "ELISA",
    nameEn: "ELISA",
    aliases: ["ELISA", "Enzyme-linked immunosorbent assay", "酶联免疫吸附实验", "酶联免疫吸附测定"],
    descriptionZh: "以包被、封闭、洗板、检测抗体和显色底物为核心的蛋白定量检测。",
    descriptionEn: "Plate-based protein quantification workflow with coating, blocking, wash, detection antibody and substrate.",
    supportsManualResolution: true,
  },
  {
    code: "FLOW",
    nameZh: "流式细胞术",
    nameEn: "Flow Cytometry",
    aliases: ["FLOW", "FACS", "Flow cytometry", "流式细胞术", "流式检测"],
    descriptionZh: "以流式染色、荧光抗体和活死染为核心的细胞表型检测。",
    descriptionEn: "Cell-phenotyping workflow using flow staining buffers, fluorescent antibodies and viability dye.",
    supportsManualResolution: true,
  },
] as const;

export type ExperimentTypeCode = (typeof experimentTypeCatalog)[number]["code"];

export const researchDirectionCatalog = [
  { code: "AUTOPHAGY", nameZh: "自噬", nameEn: "Autophagy" },
  { code: "SECRETORY_AUTOPHAGY", nameZh: "分泌性自噬", nameEn: "Secretory autophagy" },
  { code: "EXOSOME", nameZh: "细胞外囊泡/外泌体", nameEn: "Extracellular vesicles and exosomes" },
  { code: "ECM_REMODELING", nameZh: "细胞外基质与基质重塑", nameEn: "Extracellular matrix and remodeling" },
  { code: "MITOCHONDRIAL_METABOLISM", nameZh: "线粒体代谢与氧化磷酸化", nameEn: "Mitochondrial metabolism and oxidative phosphorylation" },
  { code: "TGF_BETA_SMAD_SIGNALING", nameZh: "TGF-β/SMAD信号与纤维化", nameEn: "TGF-β/SMAD signaling and fibrosis" },
  { code: "WNT_BETA_CATENIN_SIGNALING", nameZh: "WNT/β-catenin信号", nameEn: "WNT/β-catenin signaling" },
  { code: "PI3K_AKT_MTOR_SIGNALING", nameZh: "PI3K-AKT-mTOR信号", nameEn: "PI3K-AKT-mTOR signaling" },
  { code: "MAPK_ERK_SIGNALING", nameZh: "MAPK/ERK信号", nameEn: "MAPK/ERK signaling" },
  { code: "NF_KAPPA_B_INFLAMMATION", nameZh: "NF-κB炎症信号", nameEn: "NF-κB inflammatory signaling" },
  { code: "CALCIUM_SIGNALING", nameZh: "钙信号", nameEn: "Calcium signaling" },
  { code: "GLUCOSE_METABOLISM", nameZh: "葡萄糖代谢与糖酵解", nameEn: "Glucose metabolism and glycolysis" },
  { code: "LIPID_METABOLISM", nameZh: "脂质代谢与脂滴表型", nameEn: "Lipid metabolism and lipid-droplet phenotypes" },
  { code: "FERROPTOSIS", nameZh: "铁死亡", nameEn: "Ferroptosis" },
  { code: "NECROPTOSIS", nameZh: "程序性坏死", nameEn: "Necroptosis" },
  { code: "LYSOSOMAL_FUNCTION", nameZh: "溶酶体功能", nameEn: "Lysosomal function" },
  { code: "CELL_ADHESION_CYTOSKELETON", nameZh: "细胞黏附、骨架与力学转导", nameEn: "Cell adhesion, cytoskeleton, and mechanotransduction" },
  { code: "CIRCADIAN_RHYTHM", nameZh: "昼夜节律与时间生物学", nameEn: "Circadian rhythm and chronobiology" },
  { code: "EPIGENETIC_REPROGRAMMING", nameZh: "表观遗传重编程", nameEn: "Epigenetic reprogramming" },
  { code: "DNA_METHYLATION_HYDROXYMETHYLATION", nameZh: "DNA甲基化与羟甲基化", nameEn: "DNA methylation and hydroxymethylation" },
  { code: "HISTONE_ACETYLATION", nameZh: "组蛋白乙酰化", nameEn: "Histone acetylation" },
  { code: "HISTONE_METHYLATION", nameZh: "组蛋白甲基化", nameEn: "Histone methylation" },
  { code: "HISTONE_LACTYLATION", nameZh: "组蛋白乳酸化", nameEn: "Histone lactylation" },
  { code: "CHROMATIN_ACCESSIBILITY_ARCHITECTURE", nameZh: "染色质可及性与核内结构", nameEn: "Chromatin accessibility and nuclear architecture" },
  { code: "PROTEIN_PHOSPHORYLATION_KINASE_SIGNALING", nameZh: "蛋白质磷酸化与激酶信号", nameEn: "Protein phosphorylation and kinase signaling" },
  { code: "NOTCH_HEDGEHOG_SIGNALING", nameZh: "Notch/Hedgehog发育信号", nameEn: "Notch/Hedgehog developmental signaling" },
  { code: "INNATE_INFLAMMATION_INFLAMMASOME", nameZh: "先天炎症与炎症小体", nameEn: "Innate inflammation and inflammasome" },
  { code: "T_CELL_IMMUNITY", nameZh: "T细胞免疫", nameEn: "T-cell immunity" },
  { code: "B_CELL_HUMORAL_IMMUNITY", nameZh: "B细胞与体液免疫", nameEn: "B-cell and humoral immunity" },
  { code: "NK_CELL_CYTOTOXICITY", nameZh: "NK细胞与细胞毒性", nameEn: "NK-cell cytotoxicity" },
  { code: "MYELOID_INNATE_IMMUNITY", nameZh: "髓系与先天免疫", nameEn: "Myeloid and innate immunity" },
  { code: "IMMUNE_CHECKPOINT_SUPPRESSION", nameZh: "免疫检查点与免疫抑制", nameEn: "Immune checkpoints and suppression" },
  { code: "IMMUNE_METABOLISM", nameZh: "免疫代谢", nameEn: "Immune metabolism" },
  { code: "ANTIGEN_PRESENTATION", nameZh: "抗原加工与呈递", nameEn: "Antigen processing and presentation" },
  { code: "COMPLEMENT_FC_EFFECTOR", nameZh: "补体与Fc效应功能", nameEn: "Complement and Fc effector function" },
  { code: "IMMUNE_TRAFFICKING", nameZh: "免疫细胞趋化、迁移与组织浸润", nameEn: "Immune-cell chemotaxis, migration, and tissue infiltration" },
  { code: "CELL_CYCLE_DNA_DAMAGE", nameZh: "细胞周期与DNA损伤", nameEn: "Cell cycle and DNA damage" },
  { code: "CELL_DEATH_STRESS", nameZh: "细胞死亡与应激", nameEn: "Cell death and stress" },
  { code: "SENESCENCE_SASP", nameZh: "细胞衰老与SASP", nameEn: "Senescence and SASP" },
  { code: "EMT_INVASION", nameZh: "EMT、迁移与侵袭", nameEn: "EMT, migration, and invasion" },
  { code: "ANGIOGENESIS_HYPOXIA", nameZh: "血管生成与缺氧", nameEn: "Angiogenesis and hypoxia" },
  { code: "METABOLIC_REPROGRAMMING", nameZh: "代谢重编程", nameEn: "Metabolic reprogramming" },
  { code: "PROTEOSTASIS_ER_STRESS", nameZh: "蛋白稳态与内质网应激", nameEn: "Proteostasis and ER stress" },
  { code: "STEMNESS_DIFFERENTIATION", nameZh: "干性与分化", nameEn: "Stemness and differentiation" },
] as const;

export const targetAliasGroups: Record<string, string[]> = {
  GAPDH: ["GAPDH"],
  ACTB: ["ACTB", "BETA ACTIN", "BETA-ACTIN", "Β ACTIN"],
  TUBULIN: ["TUBULIN", "BETA TUBULIN", "BETA-TUBULIN", "TUBB", "TUBA"],
  LC3: ["LC3", "LC3A", "LC3B", "MAP1LC3B"],
  P62: ["P62", "SQSTM1"],
  CD9: ["CD9"],
  CD63: ["CD63"],
  CD81: ["CD81"],
  TSG101: ["TSG101"],
  ALIX: ["ALIX", "PDCD6IP"],
  CALNEXIN: ["CALNEXIN", "CANX"],
  GM130: ["GM130", "GOLGA2"],
  SYNTENIN: ["SYNTENIN", "SYNTENIN-1", "SDCBP"],
  BECN1: ["BECN1", "BECLIN1", "BECLIN-1"],
  ATG5: ["ATG5"],
  ATG7: ["ATG7"],
  ULK1: ["ULK1"],
  LAMP1: ["LAMP1", "CD107A"],
  LAMP2: ["LAMP2"],
  COL1A1: ["COL1A1", "COLLAGEN I", "COLLAGEN TYPE I"],
  COL3A1: ["COL3A1", "COLLAGEN III", "COLLAGEN TYPE III"],
  COL4A1: ["COL4A1", "COLLAGEN IV", "COLLAGEN TYPE IV"],
  FN1: ["FN1", "FIBRONECTIN"],
  LAMA1: ["LAMA1", "LAMININ"],
  MMP2: ["MMP2", "MMP-2"],
  MMP9: ["MMP9", "MMP-9"],
  TIMP1: ["TIMP1", "TIMP-1"],
  LOX: ["LOX", "LYSYL OXIDASE"],
  TOMM20: ["TOMM20", "TOM20"],
  VDAC1: ["VDAC1", "VDAC"],
  COX4I1: ["COX4I1", "COX4", "COX IV", "COX-4"],
  TFAM: ["TFAM"],
  PPARGC1A: ["PPARGC1A", "PGC1A", "PGC-1A", "PGC-1ALPHA"],
  DNMT1: ["DNMT1"],
  DNMT3A: ["DNMT3A"],
  TET1: ["TET1"],
  TET2: ["TET2"],
  H3K27AC: ["H3K27AC", "H3K27ACETYL", "H3K27 AC"],
  H3K9AC: ["H3K9AC", "H3K9ACETYL", "H3K9 AC"],
  H3K4ME3: ["H3K4ME3", "H3K4 TRI-METHYL", "H3K4 TRIMETHYL"],
  H3K27ME3: ["H3K27ME3", "H3K27 TRI-METHYL", "H3K27 TRIMETHYL"],
  H3K9ME3: ["H3K9ME3", "H3K9 TRI-METHYL", "H3K9 TRIMETHYL"],
  H3K18LA: ["H3K18LA", "H3K18 LAC", "H3K18 LACTYLATION"],
  PANKLA: ["PAN KLA", "PAN-KLA", "PAN LYSINE LACTYLATION"],
  EZH2: ["EZH2"],
  EP300: ["EP300", "P300"],
  HDAC1: ["HDAC1"],
  CTNNB1: ["CTNNB1", "BETA CATENIN", "Β-CATENIN"],
  AKT1: ["AKT1", "AKT", "P-AKT", "PHOSPHO-AKT"],
  MAPK1: ["MAPK1", "ERK2", "ERK", "P-ERK", "PHOSPHO-ERK"],
  RELA: ["RELA", "P65", "NF-KB P65", "NFKB P65"],
  NFKBIA: ["NFKBIA", "I KAPPA B ALPHA", "IKBA", "IκBα"],
  IFNB1: ["IFNB1", "IFN-B", "IFN-BETA", "INTERFERON BETA"],
  IFNG: ["IFNG", "IFN-G", "IFN-GAMMA", "INTERFERON GAMMA"],
  IFNAR1: ["IFNAR1", "IFNAR"],
  IFNGR1: ["IFNGR1", "IFNGR"],
  STAT1: ["STAT1", "P-STAT1", "PSTAT1", "PHOSPHO-STAT1"],
  IRF3: ["IRF3", "P-IRF3", "PIRF3", "PHOSPHO-IRF3"],
  ISG15: ["ISG15"],
  MX1: ["MX1", "MXA"],
  OAS1: ["OAS1"],
  CXCL10: ["CXCL10", "IP-10"],
  NLRP3: ["NLRP3"],
  CASP1: ["CASP1", "CASPASE-1", "CASPASE 1"],
  GSDMD: ["GSDMD", "GASDERMIN D"],
  IL1B: ["IL1B", "IL-1B", "IL-1BETA"],
  CD3: ["CD3", "CD3D", "CD3E", "TCR"],
  CD4: ["CD4"],
  CD8A: ["CD8A", "CD8"],
  FOXP3: ["FOXP3"],
  PDCD1: ["PDCD1", "PD-1", "PD1"],
  CD274: ["CD274", "PD-L1", "PDL1"],
  CTLA4: ["CTLA4", "CTLA-4"],
  LAG3: ["LAG3", "LAG-3"],
  TIGIT: ["TIGIT"],
  HAVCR2: ["HAVCR2", "TIM-3", "TIM3"],
  CD19: ["CD19"],
  MS4A1: ["MS4A1", "CD20"],
  CD79A: ["CD79A", "MB-1", "MB1"],
  CD27: ["CD27"],
  SDC1: ["SDC1", "CD138"],
  NCAM1: ["NCAM1", "CD56"],
  FCGR3A: ["FCGR3A", "CD16"],
  KLRD1: ["KLRD1", "CD94"],
  NCR1: ["NCR1", "NKP46", "NKP-46"],
  NKG7: ["NKG7"],
  GNLY: ["GNLY", "GRANULYSIN"],
  PRF1: ["PRF1", "PERFORIN"],
  GZMB: ["GZMB", "GRANZYME B"],
  CD14: ["CD14"],
  ITGAM: ["ITGAM", "CD11B"],
  CD68: ["CD68"],
  CD163: ["CD163"],
  MRC1: ["MRC1", "CD206"],
  NOS2: ["NOS2", "INOS"],
  ARG1: ["ARG1", "ARGINASE-1", "ARGINASE 1"],
  HLA_DRA: ["HLA-DRA", "HLA DRA", "MHC II", "MHC-II"],
  HLA_A: ["HLA-A", "HLA A", "MHC I", "MHC-I"],
  B2M: ["B2M", "BETA-2 MICROGLOBULIN"],
  TAP1: ["TAP1"],
  CD74: ["CD74", "INVARIANT CHAIN"],
  C3: ["C3", "COMPLEMENT C3"],
  C5: ["C5", "COMPLEMENT C5"],
  C3AR1: ["C3AR1", "C3A RECEPTOR", "C3AR"],
  C5AR1: ["C5AR1", "C5A RECEPTOR", "CD88"],
};

function normalizeToken(input: string) {
  return input
    .normalize("NFKC")
    .replace(/[αΑ]/g, " ALPHA ")
    .replace(/[βΒ]/g, " BETA ")
    .replace(/[γΓ]/g, " GAMMA ")
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const aliasToCanonical = new Map<string, string>();
for (const [canonical, aliases] of Object.entries(targetAliasGroups)) {
  aliasToCanonical.set(normalizeToken(canonical), canonical);
  for (const alias of aliases) {
    aliasToCanonical.set(normalizeToken(alias), canonical);
  }
}

export function normalizeTargetName(target?: string | null) {
  if (!target) return null;
  const normalized = normalizeToken(target);
  return aliasToCanonical.get(normalized) ?? normalized;
}

export const ruleCatalog: RuleDefinition[] = [
  {
    experimentCode: "WB",
    level: "MIN_REQUIRED",
    displayNameZh: "WB 需要裂解/样本制备试剂",
    displayNameEn: "WB needs lysis or sample preparation reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_LYSIS_BUFFER"],
  },
  {
    experimentCode: "WB",
    level: "MIN_REQUIRED",
    displayNameZh: "WB 需要上样缓冲液",
    displayNameEn: "WB needs loading buffer",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_LOADING_BUFFER"],
  },
  {
    experimentCode: "WB",
    level: "MIN_REQUIRED",
    displayNameZh: "WB 需要目标一抗",
    displayNameEn: "WB needs a target primary antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: [],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    level: "MIN_REQUIRED",
    displayNameZh: "WB 需要二抗",
    displayNameEn: "WB needs a secondary antibody",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_SECONDARY_ANTIBODY"],
  },
  {
    experimentCode: "WB",
    level: "MIN_REQUIRED",
    displayNameZh: "WB 至少一个内参",
    displayNameEn: "WB needs at least one loading control",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["GAPDH", "ACTB", "TUBULIN"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    level: "MIN_REQUIRED",
    displayNameZh: "WB 需要检测底物",
    displayNameEn: "WB needs a detection substrate",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_DETECTION_SUBSTRATE"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 WB 封闭液",
    displayNameEn: "Recommended WB blocking buffer",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_BLOCKING_BUFFER"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 WB 洗膜缓冲液",
    displayNameEn: "Recommended WB wash buffer",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_WASH_BUFFER"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 WB 转印相关试剂",
    displayNameEn: "Recommended WB transfer reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_TRANSFER_REAGENT"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 WB 转印膜",
    displayNameEn: "Recommended WB transfer membrane",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_TRANSFER_MEMBRANE"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充蛋白酶抑制剂",
    displayNameEn: "Recommended protease inhibitor",
    matcherType: "TAG_ANY",
    matcherValues: ["PROTEASE_INHIBITOR"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充磷酸酶抑制剂",
    displayNameEn: "Recommended phosphatase inhibitor",
    matcherType: "TAG_ANY",
    matcherValues: ["PHOSPHATASE_INHIBITOR"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充蛋白定量试剂",
    displayNameEn: "Recommended protein quantification reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["PROTEIN_QUANTIFICATION_REAGENT"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充还原剂",
    displayNameEn: "Recommended reducing agent",
    matcherType: "TAG_ANY",
    matcherValues: ["REDUCING_AGENT"],
  },
  {
    experimentCode: "QPCR",
    level: "MIN_REQUIRED",
    displayNameZh: "qPCR 需要 RNA 提取试剂",
    displayNameEn: "qPCR needs RNA extraction reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["RNA_EXTRACTION_REAGENT"],
  },
  {
    experimentCode: "QPCR",
    level: "MIN_REQUIRED",
    displayNameZh: "qPCR 需要逆转录试剂",
    displayNameEn: "qPCR needs reverse transcription reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["REVERSE_TRANSCRIPTION_REAGENT"],
  },
  {
    experimentCode: "QPCR",
    level: "MIN_REQUIRED",
    displayNameZh: "qPCR 需要 qPCR 扩增体系",
    displayNameEn: "qPCR needs master mix",
    matcherType: "TAG_ANY",
    matcherValues: ["QPCR_MASTER_MIX"],
  },
  {
    experimentCode: "QPCR",
    level: "MIN_REQUIRED",
    displayNameZh: "qPCR 需要目标基因引物",
    displayNameEn: "qPCR needs target primers",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: [],
  },
  {
    experimentCode: "QPCR",
    level: "MIN_REQUIRED",
    displayNameZh: "qPCR 至少一个内参引物",
    displayNameEn: "qPCR needs at least one reference primer",
    matcherType: "PRIMER_REFERENCE",
    matcherValues: [],
  },
  {
    experimentCode: "QPCR",
    level: "MIN_REQUIRED",
    displayNameZh: "qPCR 需要无核酸酶水",
    displayNameEn: "qPCR needs nuclease-free water",
    matcherType: "TAG_ANY",
    matcherValues: ["NUCLEASE_FREE_WATER"],
  },
  {
    experimentCode: "QPCR",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 DNase 去基因组污染试剂",
    displayNameEn: "Recommended DNase reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["DNASE_REAGENT"],
  },
  {
    experimentCode: "QPCR",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 RNase inhibitor",
    displayNameEn: "Recommended RNase inhibitor",
    matcherType: "TAG_ANY",
    matcherValues: ["RNASE_INHIBITOR"],
  },
  {
    experimentCode: "QPCR",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充细胞培养基",
    displayNameEn: "Recommended cell culture medium",
    matcherType: "TAG_ANY",
    matcherValues: ["CELL_CULTURE_MEDIUM"],
  },
  {
    experimentCode: "QPCR",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充血清添加物",
    displayNameEn: "Recommended serum supplement",
    matcherType: "TAG_ANY",
    matcherValues: ["SERUM_SUPPLEMENT"],
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要固定液",
    displayNameEn: "IF needs fixative",
    matcherType: "TAG_ANY",
    matcherValues: ["FIXATIVE"],
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要透化试剂",
    displayNameEn: "IF needs permeabilization reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["PERMEABILIZATION_REAGENT"],
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要封闭液",
    displayNameEn: "IF needs blocking reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["BLOCKING_REAGENT"],
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要目标一抗",
    displayNameEn: "IF needs a target primary antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: [],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要荧光二抗",
    displayNameEn: "IF needs fluorescent secondary antibody",
    matcherType: "TAG_ANY",
    matcherValues: ["IF_FLUORESCENT_SECONDARY_ANTIBODY"],
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要核染",
    displayNameEn: "IF needs nuclear stain",
    matcherType: "TAG_ANY",
    matcherValues: ["NUCLEAR_STAIN"],
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要封片/抗淬灭介质",
    displayNameEn: "IF needs mounting medium",
    matcherType: "TAG_ANY",
    matcherValues: ["MOUNTING_MEDIUM"],
  },
  {
    experimentCode: "IF",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 IF 洗液",
    displayNameEn: "Recommended IF wash buffer",
    matcherType: "TAG_ANY",
    matcherValues: ["IF_WASH_BUFFER"],
  },
  {
    experimentCode: "IF",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充细胞骨架染料",
    displayNameEn: "Recommended cytoskeleton stain",
    matcherType: "TAG_ANY",
    matcherValues: ["CYTOSKELETON_STAIN"],
  },
  {
    experimentCode: "IF",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充细胞器染料",
    displayNameEn: "Recommended organelle stain",
    matcherType: "TAG_ANY",
    matcherValues: ["ORGANELLE_STAIN"],
  },
  {
    experimentCode: "IF",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充细胞培养基",
    displayNameEn: "Recommended cell culture medium",
    matcherType: "TAG_ANY",
    matcherValues: ["CELL_CULTURE_MEDIUM"],
  },
  {
    experimentCode: "IF",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充血清添加物",
    displayNameEn: "Recommended serum supplement",
    matcherType: "TAG_ANY",
    matcherValues: ["SERUM_SUPPLEMENT"],
  },
  {
    experimentCode: "ELISA",
    level: "MIN_REQUIRED",
    displayNameZh: "ELISA 需要包被相关试剂",
    displayNameEn: "ELISA needs coating reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["ELISA_COATING_REAGENT"],
  },
  {
    experimentCode: "ELISA",
    level: "MIN_REQUIRED",
    displayNameZh: "ELISA 需要封闭液",
    displayNameEn: "ELISA needs blocking reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["ELISA_BLOCKING_REAGENT"],
  },
  {
    experimentCode: "ELISA",
    level: "MIN_REQUIRED",
    displayNameZh: "ELISA 需要洗板缓冲液",
    displayNameEn: "ELISA needs wash buffer",
    matcherType: "TAG_ANY",
    matcherValues: ["ELISA_WASH_BUFFER"],
  },
  {
    experimentCode: "ELISA",
    level: "MIN_REQUIRED",
    displayNameZh: "ELISA 需要检测抗体",
    displayNameEn: "ELISA needs detection antibody",
    matcherType: "TAG_ANY",
    matcherValues: ["ELISA_DETECTION_ANTIBODY"],
  },
  {
    experimentCode: "ELISA",
    level: "MIN_REQUIRED",
    displayNameZh: "ELISA 需要显色底物",
    displayNameEn: "ELISA needs substrate",
    matcherType: "TAG_ANY",
    matcherValues: ["ELISA_SUBSTRATE"],
  },
  {
    experimentCode: "ELISA",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充细胞刺激或处理试剂",
    displayNameEn: "Recommended stimulation or treatment reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["CELL_STIMULATION_REAGENT", "SIGNALING_MODULATOR"],
  },
  {
    experimentCode: "FLOW",
    level: "MIN_REQUIRED",
    displayNameZh: "流式需要荧光抗体",
    displayNameEn: "Flow cytometry needs fluorescent antibody",
    matcherType: "TAG_ANY",
    matcherValues: ["FLOW_FLUORESCENT_ANTIBODY"],
  },
  {
    experimentCode: "FLOW",
    level: "MIN_REQUIRED",
    displayNameZh: "流式需要染色缓冲液",
    displayNameEn: "Flow cytometry needs stain buffer",
    matcherType: "TAG_ANY",
    matcherValues: ["FLOW_STAIN_BUFFER"],
  },
  {
    experimentCode: "FLOW",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充活死染",
    displayNameEn: "Recommended viability dye",
    matcherType: "TAG_ANY",
    matcherValues: ["FLOW_VIABILITY_DYE"],
  },
  {
    experimentCode: "FLOW",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充一抗或待检 marker 抗体",
    displayNameEn: "Recommended primary or marker antibody",
    matcherType: "TAG_ANY",
    matcherValues: ["FLOW_PRIMARY_ANTIBODY"],
  },
  {
    experimentCode: "WB",
    directionCode: "AUTOPHAGY",
    level: "MIN_REQUIRED",
    displayNameZh: "自噬 WB 需要 LC3",
    displayNameEn: "Autophagy WB needs LC3",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["LC3"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "AUTOPHAGY",
    level: "MIN_REQUIRED",
    displayNameZh: "自噬 WB 需要 p62",
    displayNameEn: "Autophagy WB needs p62",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["P62"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "MIN_REQUIRED",
    displayNameZh: "分泌性自噬 WB 需要 LC3",
    displayNameEn: "Secretory autophagy WB needs LC3",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["LC3"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "MIN_REQUIRED",
    displayNameZh: "分泌性自噬 WB 需要 p62",
    displayNameEn: "Secretory autophagy WB needs p62",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["P62"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "QPCR",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充自噬相关 LC3 引物",
    displayNameEn: "Recommended autophagy LC3 primer",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["LC3"],
  },
  {
    experimentCode: "QPCR",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充自噬相关 p62 引物",
    displayNameEn: "Recommended autophagy p62 primer",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["P62"],
  },
  {
    experimentCode: "WB",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充转染/基因递送试剂以做自噬干预",
    displayNameEn: "Recommended transfection or gene delivery reagent for autophagy perturbation",
    matcherType: "TAG_ANY",
    matcherValues: ["TRANSFECTION_REAGENT", "GENE_DELIVERY_REAGENT"],
  },
  {
    experimentCode: "QPCR",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充分泌性自噬相关 LC3 引物",
    displayNameEn: "Recommended secretory autophagy LC3 primer",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["LC3"],
  },
  {
    experimentCode: "QPCR",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充分泌性自噬相关 p62 引物",
    displayNameEn: "Recommended secretory autophagy p62 primer",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["P62"],
  },
  {
    experimentCode: "WB",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充转染/基因递送试剂以做分泌性自噬干预",
    displayNameEn: "Recommended transfection or gene delivery reagent for secretory autophagy perturbation",
    matcherType: "TAG_ANY",
    matcherValues: ["TRANSFECTION_REAGENT", "GENE_DELIVERY_REAGENT"],
  },
  {
    experimentCode: "IF",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充自噬相关抗体（LC3 或 p62）",
    displayNameEn: "Recommended autophagy antibody (LC3 or p62)",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["LC3", "P62"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "IF",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充转染/基因递送试剂以做自噬干预",
    displayNameEn: "Recommended transfection or gene delivery reagent for autophagy perturbation",
    matcherType: "TAG_ANY",
    matcherValues: ["TRANSFECTION_REAGENT", "GENE_DELIVERY_REAGENT"],
  },
  {
    experimentCode: "IF",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充分泌性自噬相关抗体（LC3 或 p62）",
    displayNameEn: "Recommended secretory autophagy antibody (LC3 or p62)",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["LC3", "P62"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "IF",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充转染/基因递送试剂以做分泌性自噬干预",
    displayNameEn: "Recommended transfection or gene delivery reagent for secretory autophagy perturbation",
    matcherType: "TAG_ANY",
    matcherValues: ["TRANSFECTION_REAGENT", "GENE_DELIVERY_REAGENT"],
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "MIN_REQUIRED",
    displayNameZh: "外泌体 WB 需要至少一个 tetraspanin 标志物",
    displayNameEn: "Exosome WB needs at least one tetraspanin marker",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["CD9", "CD63", "CD81"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "MIN_REQUIRED",
    displayNameZh: "外泌体 WB 需要至少一个内体/胞质相关标志物",
    displayNameEn: "Exosome WB needs at least one endosomal or cytosolic marker",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["TSG101", "ALIX"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 Calnexin 作为污染排查",
    displayNameEn: "Recommended Calnexin contamination control",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["CALNEXIN"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充外泌体分离试剂",
    displayNameEn: "Recommended exosome isolation reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["EXOSOME_ISOLATION_REAGENT"],
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充细胞培养基",
    displayNameEn: "Recommended cell culture medium",
    matcherType: "TAG_ANY",
    matcherValues: ["CELL_CULTURE_MEDIUM"],
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充血清添加物",
    displayNameEn: "Recommended serum supplement",
    matcherType: "TAG_ANY",
    matcherValues: ["SERUM_SUPPLEMENT"],
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充去外泌体血清以降低培养来源背景",
    displayNameEn: "Recommended exosome-depleted serum to reduce culture-derived background",
    matcherType: "TAG_ANY",
    matcherValues: ["EXOSOME_DEPLETED_SERUM"],
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充外泌体免疫捕获试剂用于正交富集验证",
    displayNameEn: "Recommended EV immunocapture reagent for orthogonal enrichment validation",
    matcherType: "TAG_ANY",
    matcherValues: ["EXOSOME_CAPTURE_REAGENT"],
  },
  {
    experimentCode: "WB",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充自噬起始/延伸标志物抗体（BECN1、ATG5、ATG7 或 ULK1）",
    displayNameEn: "Recommended autophagy-initiation or elongation marker antibody (BECN1, ATG5, ATG7, or ULK1)",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["BECN1", "ATG5", "ATG7", "ULK1"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充自噬通量阻断剂（如 Bafilomycin A1 或氯喹）",
    displayNameEn: "Recommended autophagic-flux inhibitor (for example Bafilomycin A1 or chloroquine)",
    matcherType: "TAG_ANY",
    matcherValues: ["AUTOPHAGY_FLUX_INHIBITOR"],
  },
  {
    experimentCode: "IF",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充溶酶体标志物抗体（LAMP1 或 LAMP2）以支持自噬通量定位",
    displayNameEn: "Recommended lysosomal-marker antibody (LAMP1 or LAMP2) to localize autophagic flux",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["LAMP1", "LAMP2"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "ECM_REMODELING",
    level: "MIN_REQUIRED",
    displayNameZh: "基质重塑 WB 需要至少一个结构性 ECM 标志物",
    displayNameEn: "ECM-remodeling WB needs at least one structural ECM marker",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["COL1A1", "COL3A1", "COL4A1", "FN1", "LAMA1"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "ECM_REMODELING",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 ECM 降解/交联调控标志物（MMP2、MMP9、TIMP1 或 LOX）",
    displayNameEn: "Recommended ECM-degradation or crosslinking marker (MMP2, MMP9, TIMP1, or LOX)",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["MMP2", "MMP9", "TIMP1", "LOX"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "ECM_REMODELING",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 ECM 重塑调节剂或基质降解读出试剂",
    displayNameEn: "Recommended ECM-remodeling modulator or matrix-degradation readout reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["ECM_REMODELING_MODULATOR", "ECM_DEGRADATION_ASSAY_REAGENT"],
  },
  {
    experimentCode: "QPCR",
    directionCode: "ECM_REMODELING",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 ECM 结构或重塑靶点引物",
    displayNameEn: "Recommended ECM-structural or remodeling-target primers",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["COL1A1", "COL3A1", "COL4A1", "FN1", "MMP2", "MMP9", "TIMP1", "LOX"],
  },
  {
    experimentCode: "WB",
    directionCode: "MITOCHONDRIAL_METABOLISM",
    level: "MIN_REQUIRED",
    displayNameZh: "线粒体代谢 WB 需要至少一个线粒体含量/氧化磷酸化标志物",
    displayNameEn: "Mitochondrial-metabolism WB needs at least one mitochondrial-content or OXPHOS marker",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["TOMM20", "VDAC1", "COX4I1", "TFAM"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "MITOCHONDRIAL_METABOLISM",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充线粒体呼吸/应激测试试剂",
    displayNameEn: "Recommended mitochondrial-respiration or stress-test reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["MITOCHONDRIAL_RESPIRATION_ASSAY_REAGENT", "MITOCHONDRIAL_STRESSOR"],
  },
  {
    experimentCode: "IF",
    directionCode: "MITOCHONDRIAL_METABOLISM",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充线粒体染料、膜电位或超氧探针",
    displayNameEn: "Recommended mitochondrial stain, membrane-potential dye, or superoxide probe",
    matcherType: "TAG_ANY",
    matcherValues: ["MITOCHONDRIAL_STAIN", "MITOCHONDRIAL_MEMBRANE_POTENTIAL_DYE", "MITOCHONDRIAL_SUPEROXIDE_DYE"],
  },
  {
    experimentCode: "QPCR",
    directionCode: "MITOCHONDRIAL_METABOLISM",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充线粒体生物发生/功能靶点引物",
    displayNameEn: "Recommended mitochondrial biogenesis or function-target primers",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["TFAM", "PPARGC1A", "COX4I1", "TOMM20"],
  },
  {
    experimentCode: "WB",
    directionCode: "TGF_BETA_SMAD_SIGNALING",
    level: "MIN_REQUIRED",
    displayNameZh: "TGF-β/SMAD 研究需要 SMAD 通路读出抗体",
    displayNameEn: "TGF-β/SMAD studies need a SMAD-pathway readout antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["TGFB1", "SMAD2", "SMAD3", "SMAD4"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "QPCR",
    directionCode: "TGF_BETA_SMAD_SIGNALING",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充纤维化/ECM 转录靶点引物",
    displayNameEn: "Recommended fibrosis/ECM transcription-target primers",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["COL1A1", "FN1", "ACTA2"],
  },
  {
    experimentCode: "WB",
    directionCode: "WNT_BETA_CATENIN_SIGNALING",
    level: "MIN_REQUIRED",
    displayNameZh: "WNT 研究需要 β-catenin 或受体近端读出抗体",
    displayNameEn: "WNT studies need a β-catenin or proximal-receptor readout antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["CTNNB1", "LRP6", "GSK3B"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "QPCR",
    directionCode: "WNT_BETA_CATENIN_SIGNALING",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 WNT 转录输出靶点引物",
    displayNameEn: "Recommended WNT transcription-output primers",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["AXIN2", "MYC", "LEF1"],
  },
  {
    experimentCode: "WB",
    directionCode: "PI3K_AKT_MTOR_SIGNALING",
    level: "MIN_REQUIRED",
    displayNameZh: "PI3K-AKT-mTOR 研究需要至少一个轴内蛋白读出",
    displayNameEn: "PI3K-AKT-mTOR studies need at least one axis protein readout",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["AKT1", "MTOR", "RPS6", "EIF4EBP1"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "MAPK_ERK_SIGNALING",
    level: "MIN_REQUIRED",
    displayNameZh: "MAPK/ERK 研究需要 ERK、JNK 或 p38 读出抗体",
    displayNameEn: "MAPK/ERK studies need an ERK, JNK, or p38 readout antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["MAPK1", "MAPK3", "MAPK8", "MAPK14"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "NF_KAPPA_B_INFLAMMATION",
    level: "MIN_REQUIRED",
    displayNameZh: "NF-κB 研究需要 p65 或 IκBα 读出抗体",
    displayNameEn: "NF-κB studies need p65 or IκBα readout antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["RELA", "NFKBIA"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "QPCR",
    directionCode: "NF_KAPPA_B_INFLAMMATION",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 NF-κB 炎症转录输出引物",
    displayNameEn: "Recommended NF-κB inflammatory-output primers",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["IL6", "TNF", "CXCL8"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "CALCIUM_SIGNALING",
    level: "MIN_REQUIRED",
    displayNameZh: "钙信号研究需要钙通量探针",
    displayNameEn: "Calcium-signaling studies need a calcium-flux probe",
    matcherType: "NAME_ANY",
    matcherValues: ["fluo-4", "fura-2", "calcium flux"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "GLUCOSE_METABOLISM",
    level: "MIN_REQUIRED",
    displayNameZh: "葡萄糖代谢研究需要葡萄糖摄取或糖酵解读出试剂",
    displayNameEn: "Glucose-metabolism studies need glucose-uptake or glycolysis readout reagent",
    matcherType: "NAME_ANY",
    matcherValues: ["2-nbdg", "2-deoxy", "lactate assay"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "LIPID_METABOLISM",
    level: "MIN_REQUIRED",
    displayNameZh: "脂质代谢研究需要脂滴或脂肪酸读出探针",
    displayNameEn: "Lipid-metabolism studies need a lipid-droplet or fatty-acid readout probe",
    matcherType: "NAME_ANY",
    matcherValues: ["bodipy", "nile red", "fatty acid uptake"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "FERROPTOSIS",
    level: "MIN_REQUIRED",
    displayNameZh: "铁死亡研究需要脂质过氧化读出探针",
    displayNameEn: "Ferroptosis studies need a lipid-peroxidation readout probe",
    matcherType: "NAME_ANY",
    matcherValues: ["c11-bodipy", "lipid peroxidation"],
  },
  {
    experimentCode: "WB",
    directionCode: "FERROPTOSIS",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 GPX4/SLC7A11/ACSL4 抗体",
    displayNameEn: "Recommended GPX4/SLC7A11/ACSL4 antibodies",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["GPX4", "SLC7A11", "ACSL4"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "NECROPTOSIS",
    level: "MIN_REQUIRED",
    displayNameZh: "程序性坏死研究需要 RIPK1/RIPK3/MLKL 轴读出抗体",
    displayNameEn: "Necroptosis studies need RIPK1/RIPK3/MLKL-axis readout antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["RIPK1", "RIPK3", "MLKL"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "IF",
    directionCode: "LYSOSOMAL_FUNCTION",
    level: "MIN_REQUIRED",
    displayNameZh: "溶酶体功能研究需要溶酶体定位或活性读出",
    displayNameEn: "Lysosomal-function studies need lysosomal localization or activity readout",
    matcherType: "NAME_ANY",
    matcherValues: ["lysotracker", "lysosensor", "cathepsin"],
  },
  {
    experimentCode: "WB",
    directionCode: "LYSOSOMAL_FUNCTION",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 LAMP 或 cathepsin 抗体",
    displayNameEn: "Recommended LAMP or cathepsin antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["LAMP1", "LAMP2", "CTSB", "CTSD"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "IF",
    directionCode: "CELL_ADHESION_CYTOSKELETON",
    level: "MIN_REQUIRED",
    displayNameZh: "细胞黏附/骨架研究需要 F-actin 或黏着斑读出",
    displayNameEn: "Cell-adhesion/cytoskeleton studies need F-actin or focal-adhesion readout",
    matcherType: "TAG_ANY",
    matcherValues: ["CYTOSKELETON_STAIN"],
  },
  {
    experimentCode: "WB",
    directionCode: "CELL_ADHESION_CYTOSKELETON",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充整合素/FAK/YAP 抗体",
    displayNameEn: "Recommended integrin/FAK/YAP antibodies",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["ITGB1", "PTK2", "YAP1"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "QPCR",
    directionCode: "CIRCADIAN_RHYTHM",
    level: "MIN_REQUIRED",
    displayNameZh: "昼夜节律研究需要核心时钟基因引物",
    displayNameEn: "Circadian studies need core-clock gene primers",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["ARNTL", "CLOCK", "PER1", "PER2", "CRY1", "CRY2"],
  },
  {
    experimentCode: "CHIP_QPCR",
    directionCode: "EPIGENETIC_REPROGRAMMING",
    level: "MIN_REQUIRED",
    displayNameZh: "表观遗传重编程需要组蛋白修饰或染色质读出抗体",
    displayNameEn: "Epigenetic-reprogramming studies need histone-mark or chromatin readout antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["H3K27AC", "H3K27ME3", "H3K4ME3"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WHOLE_GENOME_BISULFITE_SEQUENCING",
    directionCode: "DNA_METHYLATION_HYDROXYMETHYLATION",
    level: "MIN_REQUIRED",
    displayNameZh: "DNA甲基化研究需要亚硫酸氢盐转换试剂",
    displayNameEn: "DNA-methylation studies need bisulfite-conversion chemistry",
    matcherType: "TAG_ANY",
    matcherValues: ["BISULFITE_CONVERSION_REAGENT"],
  },
  {
    experimentCode: "QPCR",
    directionCode: "DNA_METHYLATION_HYDROXYMETHYLATION",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充DNMT/TET或候选甲基化位点引物",
    displayNameEn: "Recommended DNMT/TET or candidate methylation-locus primers",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["DNMT1", "DNMT3A", "TET1", "TET2"],
  },
  {
    experimentCode: "CHIP_QPCR",
    directionCode: "HISTONE_ACETYLATION",
    level: "MIN_REQUIRED",
    displayNameZh: "组蛋白乙酰化研究需要乙酰化标记验证抗体",
    displayNameEn: "Histone-acetylation studies need a validated acetylation-mark antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["H3K27AC", "H3K9AC"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "CHIP_QPCR",
    directionCode: "HISTONE_METHYLATION",
    level: "MIN_REQUIRED",
    displayNameZh: "组蛋白甲基化研究需要甲基化标记验证抗体",
    displayNameEn: "Histone-methylation studies need a validated methylation-mark antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["H3K4ME3", "H3K27ME3", "H3K9ME3"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "HISTONE_LACTYLATION",
    level: "MIN_REQUIRED",
    displayNameZh: "组蛋白乳酸化研究需要乳酸化标记抗体",
    displayNameEn: "Histone-lactylation studies need a lactylation-mark antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["PANKLA", "H3K18LA"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "HISTONE_LACTYLATION",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充乳酸或糖酵解调节试剂",
    displayNameEn: "Recommended lactate or glycolysis-modulation reagent",
    matcherType: "NAME_ANY",
    matcherValues: ["lactate", "sodium lactate", "2-deoxy", "oxamate"],
  },
  {
    experimentCode: "ATAC_QPCR",
    directionCode: "CHROMATIN_ACCESSIBILITY_ARCHITECTURE",
    level: "MIN_REQUIRED",
    displayNameZh: "染色质可及性研究需要转座酶与细胞核分离试剂",
    displayNameEn: "Chromatin-accessibility studies need transposase and nuclei-isolation reagents",
    matcherType: "TAG_ANY",
    matcherValues: ["TRANSPOSASE_REAGENT", "NUCLEI_ISOLATION_REAGENT"],
  },
  {
    experimentCode: "PHOSPHOPROTEOMICS",
    directionCode: "PROTEIN_PHOSPHORYLATION_KINASE_SIGNALING",
    level: "MIN_REQUIRED",
    displayNameZh: "磷酸化组学需要磷酸肽富集试剂",
    displayNameEn: "Phosphorylation studies need phosphopeptide-enrichment reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["PHOSPHOPEPTIDE_ENRICHMENT_REAGENT"],
  },
  {
    experimentCode: "WB",
    directionCode: "PROTEIN_PHOSPHORYLATION_KINASE_SIGNALING",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充磷酸化位点与对应总蛋白抗体对",
    displayNameEn: "Recommended phosphosite and corresponding total-protein antibody pairs",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["AKT1", "MAPK1", "STAT1"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "NOTCH_HEDGEHOG_SIGNALING",
    level: "MIN_REQUIRED",
    displayNameZh: "Notch/Hedgehog 研究需要 NICD、SMO 或 GLI 读出抗体",
    displayNameEn: "Notch/Hedgehog studies need NICD, SMO, or GLI readout antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["NOTCH1", "NICD", "SMO", "GLI1"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "QPCR",
    directionCode: "NOTCH_HEDGEHOG_SIGNALING",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 HES/GLI/PTCH 转录输出引物",
    displayNameEn: "Recommended HES/GLI/PTCH transcription-output primers",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["HES1", "HEY1", "GLI1", "PTCH1"],
  },
  {
    experimentCode: "WB",
    directionCode: "INNATE_INFLAMMATION_INFLAMMASOME",
    level: "MIN_REQUIRED",
    displayNameZh: "炎症小体 WB 需要至少一个炎症小体/焦亡标志物",
    displayNameEn: "Inflammasome WB needs at least one inflammasome or pyroptosis marker",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["NLRP3", "CASP1", "GSDMD", "IL1B"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "INNATE_INFLAMMATION_INFLAMMASOME",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充先天免疫刺激剂与炎症小体激活剂",
    displayNameEn: "Recommended innate-immune stimulant and inflammasome activator",
    matcherType: "TAG_ANY",
    matcherValues: ["INNATE_IMMUNE_STIMULANT", "INFLAMMASOME_ACTIVATOR"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "INNATE_INFLAMMATION_INFLAMMASOME",
    level: "MIN_REQUIRED",
    displayNameZh: "炎性小体流式需要炎性小体激活/探针试剂",
    displayNameEn: "Inflammasome flow cytometry needs an inflammasome-activation or probe reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["INFLAMMASOME_ACTIVATOR"],
  },
  {
    experimentCode: "SANDWICH_ELISA",
    directionCode: "INNATE_INFLAMMATION_INFLAMMASOME",
    level: "MIN_REQUIRED",
    displayNameZh: "炎性小体细胞因子 ELISA 需要炎性小体激活试剂",
    displayNameEn: "Inflammasome-cytokine ELISA needs an inflammasome-activation reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["INFLAMMASOME_ACTIVATOR"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "T_CELL_IMMUNITY",
    level: "MIN_REQUIRED",
    displayNameZh: "T细胞流式需要谱系标志物抗体（CD3、CD4 或 CD8）",
    displayNameEn: "T-cell flow cytometry needs lineage-marker antibody (CD3, CD4, or CD8)",
    matcherType: "TAG_ANY",
    matcherValues: ["T_CELL_LINEAGE_MARKER_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "T_CELL_IMMUNITY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 T细胞激活/扩增试剂",
    displayNameEn: "Recommended T-cell activation or expansion reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["T_CELL_ACTIVATION_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "B_CELL_HUMORAL_IMMUNITY",
    level: "MIN_REQUIRED",
    displayNameZh: "B细胞流式需要谱系标志物抗体（CD19、CD20 或 CD79A）",
    displayNameEn: "B-cell flow cytometry needs lineage-marker antibody (CD19, CD20, or CD79A)",
    matcherType: "TAG_ANY",
    matcherValues: ["B_CELL_LINEAGE_MARKER_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "B_CELL_HUMORAL_IMMUNITY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 B细胞活化试剂",
    displayNameEn: "Recommended B-cell activation reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["B_CELL_ACTIVATION_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "NK_CELL_CYTOTOXICITY",
    level: "MIN_REQUIRED",
    displayNameZh: "NK细胞流式需要 NK 标志物抗体（CD56、CD16、CD94 或 NKp46）",
    displayNameEn: "NK-cell flow cytometry needs NK-marker antibody (CD56, CD16, CD94, or NKp46)",
    matcherType: "TAG_ANY",
    matcherValues: ["NK_CELL_MARKER_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "NK_CELL_CYTOTOXICITY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 NK细胞激活/扩增试剂",
    displayNameEn: "Recommended NK-cell activation or expansion reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["NK_CELL_ACTIVATION_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "MYELOID_INNATE_IMMUNITY",
    level: "MIN_REQUIRED",
    displayNameZh: "髓系流式需要髓系标志物抗体（CD14、CD11b、CD68、CD163、CD206 或 HLA-DR）",
    displayNameEn: "Myeloid flow cytometry needs myeloid-marker antibody (CD14, CD11b, CD68, CD163, CD206, or HLA-DR)",
    matcherType: "TAG_ANY",
    matcherValues: ["MYELOID_LINEAGE_MARKER_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "MYELOID_INNATE_IMMUNITY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充髓系极化/分化试剂",
    displayNameEn: "Recommended myeloid-polarization or differentiation reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["MYELOID_POLARIZATION_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "IMMUNE_CHECKPOINT_SUPPRESSION",
    level: "MIN_REQUIRED",
    displayNameZh: "免疫检查点流式需要检查点抗体/调节试剂",
    displayNameEn: "Immune-checkpoint flow cytometry needs checkpoint antibody or modulator",
    matcherType: "TAG_ANY",
    matcherValues: ["IMMUNE_CHECKPOINT_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "IMMUNE_CHECKPOINT_SUPPRESSION",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 T细胞谱系标志物以界定检查点表达细胞群",
    displayNameEn: "Recommended T-cell lineage marker to define checkpoint-expressing populations",
    matcherType: "TAG_ANY",
    matcherValues: ["T_CELL_LINEAGE_MARKER_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "ANTIGEN_PRESENTATION",
    level: "MIN_REQUIRED",
    displayNameZh: "抗原呈递流式需要抗原/呈递相关试剂或标志物",
    displayNameEn: "Antigen-presentation flow cytometry needs antigen or presentation-related reagent/marker",
    matcherType: "TAG_ANY",
    matcherValues: ["ANTIGEN_PRESENTATION_REAGENT"],
  },
  {
    experimentCode: "ELISA",
    directionCode: "COMPLEMENT_FC_EFFECTOR",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充补体或 Fc 效应功能试剂",
    displayNameEn: "Recommended complement or Fc-effector reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["COMPLEMENT_FC_EFFECTOR_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "COMPLEMENT_FC_EFFECTOR",
    level: "MIN_REQUIRED",
    displayNameZh: "补体/Fc效应流式需要补体或Fc效应功能试剂",
    displayNameEn: "Complement/Fc-effector flow cytometry needs a complement or Fc-effector reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["COMPLEMENT_FC_EFFECTOR_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "IMMUNE_METABOLISM",
    level: "MIN_REQUIRED",
    displayNameZh: "免疫代谢流式需要代谢调节剂或免疫亚群界定试剂",
    displayNameEn: "Immunometabolism flow cytometry needs a metabolic modulator or immune-subset definition reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["IMMUNE_METABOLISM_MODULATOR", "IMMUNE_CELL_ENRICHMENT_REAGENT", "T_CELL_LINEAGE_MARKER_REAGENT", "MYELOID_LINEAGE_MARKER_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "IMMUNE_METABOLISM",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充免疫代谢调节剂或用于界定目标群的富集/谱系试剂",
    displayNameEn: "Recommended immunometabolic modulator or enrichment/lineage reagent to define the target population",
    matcherType: "TAG_ANY",
    matcherValues: ["IMMUNE_METABOLISM_MODULATOR", "IMMUNE_CELL_ENRICHMENT_REAGENT", "T_CELL_LINEAGE_MARKER_REAGENT", "MYELOID_LINEAGE_MARKER_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "IMMUNE_TRAFFICKING",
    level: "MIN_REQUIRED",
    displayNameZh: "免疫趋化/浸润流式需要趋化因子或趋化迁移试剂",
    displayNameEn: "Immune-trafficking flow cytometry needs a chemokine or chemotaxis reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["IMMUNE_CHEMOTAXIS_REAGENT"],
  },
  {
    experimentCode: "FLOW",
    directionCode: "IMMUNE_TRAFFICKING",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充用于界定迁移细胞群的免疫谱系标志物",
    displayNameEn: "Recommended immune-lineage marker to define the migrating population",
    matcherType: "TAG_ANY",
    matcherValues: ["T_CELL_LINEAGE_MARKER_REAGENT", "MYELOID_LINEAGE_MARKER_REAGENT", "B_CELL_LINEAGE_MARKER_REAGENT", "NK_CELL_MARKER_REAGENT"],
  },
];
