export const experimentTags = [
  "CELL_CULTURE_MEDIUM",
  "SERUM_SUPPLEMENT",
  "ANTIBIOTIC_SUPPLEMENT",
  "SELECTION_ANTIBIOTIC",
  "CELL_DISSOCIATION_REAGENT",
  "CELL_FREEZING_REAGENT",
  "CELL_COUNTING_REAGENT",
  "CELL_STAIN_REAGENT",
  "CELL_CULTURE_VESSEL",
  "SYRINGE_CONSUMABLE",
  "MYCOPLASMA_TEST_REAGENT",
  "TRANSDUCTION_REAGENT",
  "GENE_DELIVERY_REAGENT",
  "CELL_STIMULATION_REAGENT",
  "SIGNALING_MODULATOR",
  "OSTEOCLAST_DIFFERENTIATION_REAGENT",
  "BONE_REMODELING_SIGNAL",
  "IMMUNE_CYTOKINE_REAGENT",
  "OSTEOGENIC_DIFFERENTIATION_REAGENT",
  "ECM_COATING_REAGENT",
  "STEM_CELL_MATRIX",
  "WB_LYSIS_BUFFER",
  "WB_LOADING_BUFFER",
  "WB_BLOCKING_BUFFER",
  "WB_WASH_BUFFER",
  "WB_TRANSFER_REAGENT",
  "WB_TRANSFER_MEMBRANE",
  "WB_PRIMARY_ANTIBODY",
  "WB_DETECTION_SUBSTRATE",
  "WB_SECONDARY_ANTIBODY",
  "PROTEASE_INHIBITOR",
  "PHOSPHATASE_INHIBITOR",
  "PROTEIN_QUANTIFICATION_REAGENT",
  "REDUCING_AGENT",
  "GEL_STAIN",
  "DNA_EXTRACTION_REAGENT",
  "RNA_EXTRACTION_REAGENT",
  "PLASMID_PREP_REAGENT",
  "PCR_MASTER_MIX",
  "REVERSE_TRANSCRIPTION_REAGENT",
  "QPCR_MASTER_MIX",
  "NUCLEASE_FREE_WATER",
  "DNASE_REAGENT",
  "RNASE_INHIBITOR",
  "TRANSFECTION_REAGENT",
  "FIXATIVE",
  "PERMEABILIZATION_REAGENT",
  "BLOCKING_REAGENT",
  "IF_PRIMARY_ANTIBODY",
  "IF_FLUORESCENT_SECONDARY_ANTIBODY",
  "NUCLEAR_STAIN",
  "CYTOSKELETON_STAIN",
  "ORGANELLE_STAIN",
  "MOUNTING_MEDIUM",
  "IF_WASH_BUFFER",
  "ELISA_COATING_REAGENT",
  "ELISA_BLOCKING_REAGENT",
  "ELISA_WASH_BUFFER",
  "ELISA_DETECTION_ANTIBODY",
  "ELISA_SUBSTRATE",
  "FLOW_PRIMARY_ANTIBODY",
  "FLOW_FLUORESCENT_ANTIBODY",
  "FLOW_STAIN_BUFFER",
  "FLOW_VIABILITY_DYE",
  "EXOSOME_ISOLATION_REAGENT",
] as const;

export type ExperimentTag = (typeof experimentTags)[number];
export type RuleLevelValue = "MIN_REQUIRED" | "RECOMMENDED";
export type MatcherTypeValue =
  | "TAG_ANY"
  | "NAME_ANY"
  | "ANTIBODY_TARGET_ANY"
  | "PRIMER_TARGET_ANY"
  | "PRIMER_REFERENCE";

export type AntibodyRoleValue = "PRIMARY" | "SECONDARY";

export type RuleDefinition = {
  experimentCode: string;
  directionCode?: string;
  level: RuleLevelValue;
  displayNameZh: string;
  displayNameEn: string;
  matcherType: MatcherTypeValue;
  matcherValues: string[];
  matcherAntibodyRole?: AntibodyRoleValue;
  requiredKeywords?: string[];
};

export type ExperimentTypeDefinition = {
  code: string;
  nameZh: string;
  nameEn: string;
  aliases: string[];
  descriptionZh: string;
  descriptionEn: string;
  supportsManualResolution: boolean;
};

export const experimentTypeCatalog: readonly ExperimentTypeDefinition[] = [
  {
    code: "WB",
    nameZh: "Western Blot",
    nameEn: "Western Blot",
    aliases: ["WB", "Western blot", "Immunoblot", "免疫印迹", "蛋白印迹"],
    descriptionZh: "蛋白电泳转膜后用抗体和底物进行条带检测。",
    descriptionEn: "Protein immunoblotting workflow with primary/secondary antibodies and detection substrate.",
    supportsManualResolution: true,
  },
  {
    code: "QPCR",
    nameZh: "qPCR",
    nameEn: "qPCR",
    aliases: ["qPCR", "RT-qPCR", "Real-time PCR", "Quantitative PCR", "实时荧光定量 PCR"],
    descriptionZh: "以 RNA 提取、逆转录和荧光定量扩增为核心的基因表达检测。",
    descriptionEn: "Gene-expression quantification workflow using RNA extraction, reverse transcription and real-time PCR.",
    supportsManualResolution: true,
  },
  {
    code: "IF",
    nameZh: "免疫荧光",
    nameEn: "Immunofluorescence",
    aliases: ["IF", "Immunofluorescence", "Immunostaining", "免疫荧光", "荧光染色"],
    descriptionZh: "通过固定、透化、抗体染色和封片进行细胞或组织成像。",
    descriptionEn: "Cell or tissue imaging workflow using fixation, permeabilization, antibody staining and mounting.",
    supportsManualResolution: true,
  },
  {
    code: "ELISA",
    nameZh: "ELISA",
    nameEn: "ELISA",
    aliases: ["ELISA", "Enzyme-linked immunosorbent assay", "酶联免疫吸附实验", "酶联免疫吸附测定"],
    descriptionZh: "以包被、封闭、洗板、检测抗体和显色底物为核心的蛋白定量检测。",
    descriptionEn: "Plate-based protein quantification workflow with coating, blocking, wash, detection antibody and substrate.",
    supportsManualResolution: true,
  },
  {
    code: "FLOW",
    nameZh: "流式细胞术",
    nameEn: "Flow Cytometry",
    aliases: ["FLOW", "FACS", "Flow cytometry", "流式细胞术", "流式检测"],
    descriptionZh: "以流式染色、荧光抗体和活死染为核心的细胞表型检测。",
    descriptionEn: "Cell-phenotyping workflow using flow staining buffers, fluorescent antibodies and viability dye.",
    supportsManualResolution: true,
  },
] as const;

export type ExperimentTypeCode = (typeof experimentTypeCatalog)[number]["code"];

export const researchDirectionCatalog = [
  { code: "AUTOPHAGY", nameZh: "自噬", nameEn: "Autophagy" },
  { code: "SECRETORY_AUTOPHAGY", nameZh: "分泌性自噬", nameEn: "Secretory autophagy" },
  { code: "EXOSOME", nameZh: "外泌体", nameEn: "Exosome" },
] as const;

export const targetAliasGroups: Record<string, string[]> = {
  GAPDH: ["GAPDH"],
  ACTB: ["ACTB", "BETA ACTIN", "BETA-ACTIN", "Β ACTIN"],
  TUBULIN: ["TUBULIN", "BETA TUBULIN", "BETA-TUBULIN", "TUBB", "TUBA"],
  LC3: ["LC3", "LC3A", "LC3B", "MAP1LC3B"],
  P62: ["P62", "SQSTM1"],
  CD9: ["CD9"],
  CD63: ["CD63"],
  CD81: ["CD81"],
  TSG101: ["TSG101"],
  ALIX: ["ALIX", "PDCD6IP"],
  CALNEXIN: ["CALNEXIN", "CANX"],
};

function normalizeToken(input: string) {
  return input.trim().toUpperCase().replace(/[^A-Z0-9]+/g, " ").replace(/\s+/g, " ").trim();
}

const aliasToCanonical = new Map<string, string>();
for (const [canonical, aliases] of Object.entries(targetAliasGroups)) {
  aliasToCanonical.set(normalizeToken(canonical), canonical);
  for (const alias of aliases) {
    aliasToCanonical.set(normalizeToken(alias), canonical);
  }
}

export function normalizeTargetName(target?: string | null) {
  if (!target) return null;
  const normalized = normalizeToken(target);
  return aliasToCanonical.get(normalized) ?? normalized;
}

export const ruleCatalog: RuleDefinition[] = [
  {
    experimentCode: "WB",
    level: "MIN_REQUIRED",
    displayNameZh: "WB 需要裂解/样本制备试剂",
    displayNameEn: "WB needs lysis or sample preparation reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_LYSIS_BUFFER"],
  },
  {
    experimentCode: "WB",
    level: "MIN_REQUIRED",
    displayNameZh: "WB 需要上样缓冲液",
    displayNameEn: "WB needs loading buffer",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_LOADING_BUFFER"],
  },
  {
    experimentCode: "WB",
    level: "MIN_REQUIRED",
    displayNameZh: "WB 需要目标一抗",
    displayNameEn: "WB needs a target primary antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: [],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    level: "MIN_REQUIRED",
    displayNameZh: "WB 需要二抗",
    displayNameEn: "WB needs a secondary antibody",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_SECONDARY_ANTIBODY"],
  },
  {
    experimentCode: "WB",
    level: "MIN_REQUIRED",
    displayNameZh: "WB 至少一个内参",
    displayNameEn: "WB needs at least one loading control",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["GAPDH", "ACTB", "TUBULIN"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    level: "MIN_REQUIRED",
    displayNameZh: "WB 需要检测底物",
    displayNameEn: "WB needs a detection substrate",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_DETECTION_SUBSTRATE"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 WB 封闭液",
    displayNameEn: "Recommended WB blocking buffer",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_BLOCKING_BUFFER"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 WB 洗膜缓冲液",
    displayNameEn: "Recommended WB wash buffer",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_WASH_BUFFER"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 WB 转印相关试剂",
    displayNameEn: "Recommended WB transfer reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_TRANSFER_REAGENT"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 WB 转印膜",
    displayNameEn: "Recommended WB transfer membrane",
    matcherType: "TAG_ANY",
    matcherValues: ["WB_TRANSFER_MEMBRANE"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充蛋白酶抑制剂",
    displayNameEn: "Recommended protease inhibitor",
    matcherType: "TAG_ANY",
    matcherValues: ["PROTEASE_INHIBITOR"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充磷酸酶抑制剂",
    displayNameEn: "Recommended phosphatase inhibitor",
    matcherType: "TAG_ANY",
    matcherValues: ["PHOSPHATASE_INHIBITOR"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充蛋白定量试剂",
    displayNameEn: "Recommended protein quantification reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["PROTEIN_QUANTIFICATION_REAGENT"],
  },
  {
    experimentCode: "WB",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充还原剂",
    displayNameEn: "Recommended reducing agent",
    matcherType: "TAG_ANY",
    matcherValues: ["REDUCING_AGENT"],
  },
  {
    experimentCode: "QPCR",
    level: "MIN_REQUIRED",
    displayNameZh: "qPCR 需要 RNA 提取试剂",
    displayNameEn: "qPCR needs RNA extraction reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["RNA_EXTRACTION_REAGENT"],
  },
  {
    experimentCode: "QPCR",
    level: "MIN_REQUIRED",
    displayNameZh: "qPCR 需要逆转录试剂",
    displayNameEn: "qPCR needs reverse transcription reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["REVERSE_TRANSCRIPTION_REAGENT"],
  },
  {
    experimentCode: "QPCR",
    level: "MIN_REQUIRED",
    displayNameZh: "qPCR 需要 qPCR 扩增体系",
    displayNameEn: "qPCR needs master mix",
    matcherType: "TAG_ANY",
    matcherValues: ["QPCR_MASTER_MIX"],
  },
  {
    experimentCode: "QPCR",
    level: "MIN_REQUIRED",
    displayNameZh: "qPCR 需要目标基因引物",
    displayNameEn: "qPCR needs target primers",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: [],
  },
  {
    experimentCode: "QPCR",
    level: "MIN_REQUIRED",
    displayNameZh: "qPCR 至少一个内参引物",
    displayNameEn: "qPCR needs at least one reference primer",
    matcherType: "PRIMER_REFERENCE",
    matcherValues: [],
  },
  {
    experimentCode: "QPCR",
    level: "MIN_REQUIRED",
    displayNameZh: "qPCR 需要无核酸酶水",
    displayNameEn: "qPCR needs nuclease-free water",
    matcherType: "TAG_ANY",
    matcherValues: ["NUCLEASE_FREE_WATER"],
  },
  {
    experimentCode: "QPCR",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 DNase 去基因组污染试剂",
    displayNameEn: "Recommended DNase reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["DNASE_REAGENT"],
  },
  {
    experimentCode: "QPCR",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 RNase inhibitor",
    displayNameEn: "Recommended RNase inhibitor",
    matcherType: "TAG_ANY",
    matcherValues: ["RNASE_INHIBITOR"],
  },
  {
    experimentCode: "QPCR",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充细胞培养基",
    displayNameEn: "Recommended cell culture medium",
    matcherType: "TAG_ANY",
    matcherValues: ["CELL_CULTURE_MEDIUM"],
  },
  {
    experimentCode: "QPCR",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充血清添加物",
    displayNameEn: "Recommended serum supplement",
    matcherType: "TAG_ANY",
    matcherValues: ["SERUM_SUPPLEMENT"],
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要固定液",
    displayNameEn: "IF needs fixative",
    matcherType: "TAG_ANY",
    matcherValues: ["FIXATIVE"],
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要透化试剂",
    displayNameEn: "IF needs permeabilization reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["PERMEABILIZATION_REAGENT"],
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要封闭液",
    displayNameEn: "IF needs blocking reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["BLOCKING_REAGENT"],
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要目标一抗",
    displayNameEn: "IF needs a target primary antibody",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: [],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要荧光二抗",
    displayNameEn: "IF needs fluorescent secondary antibody",
    matcherType: "TAG_ANY",
    matcherValues: ["IF_FLUORESCENT_SECONDARY_ANTIBODY"],
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要核染",
    displayNameEn: "IF needs nuclear stain",
    matcherType: "TAG_ANY",
    matcherValues: ["NUCLEAR_STAIN"],
  },
  {
    experimentCode: "IF",
    level: "MIN_REQUIRED",
    displayNameZh: "IF 需要封片/抗淬灭介质",
    displayNameEn: "IF needs mounting medium",
    matcherType: "TAG_ANY",
    matcherValues: ["MOUNTING_MEDIUM"],
  },
  {
    experimentCode: "IF",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 IF 洗液",
    displayNameEn: "Recommended IF wash buffer",
    matcherType: "TAG_ANY",
    matcherValues: ["IF_WASH_BUFFER"],
  },
  {
    experimentCode: "IF",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充细胞骨架染料",
    displayNameEn: "Recommended cytoskeleton stain",
    matcherType: "TAG_ANY",
    matcherValues: ["CYTOSKELETON_STAIN"],
  },
  {
    experimentCode: "IF",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充细胞器染料",
    displayNameEn: "Recommended organelle stain",
    matcherType: "TAG_ANY",
    matcherValues: ["ORGANELLE_STAIN"],
  },
  {
    experimentCode: "IF",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充细胞培养基",
    displayNameEn: "Recommended cell culture medium",
    matcherType: "TAG_ANY",
    matcherValues: ["CELL_CULTURE_MEDIUM"],
  },
  {
    experimentCode: "IF",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充血清添加物",
    displayNameEn: "Recommended serum supplement",
    matcherType: "TAG_ANY",
    matcherValues: ["SERUM_SUPPLEMENT"],
  },
  {
    experimentCode: "ELISA",
    level: "MIN_REQUIRED",
    displayNameZh: "ELISA 需要包被相关试剂",
    displayNameEn: "ELISA needs coating reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["ELISA_COATING_REAGENT"],
  },
  {
    experimentCode: "ELISA",
    level: "MIN_REQUIRED",
    displayNameZh: "ELISA 需要封闭液",
    displayNameEn: "ELISA needs blocking reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["ELISA_BLOCKING_REAGENT"],
  },
  {
    experimentCode: "ELISA",
    level: "MIN_REQUIRED",
    displayNameZh: "ELISA 需要洗板缓冲液",
    displayNameEn: "ELISA needs wash buffer",
    matcherType: "TAG_ANY",
    matcherValues: ["ELISA_WASH_BUFFER"],
  },
  {
    experimentCode: "ELISA",
    level: "MIN_REQUIRED",
    displayNameZh: "ELISA 需要检测抗体",
    displayNameEn: "ELISA needs detection antibody",
    matcherType: "TAG_ANY",
    matcherValues: ["ELISA_DETECTION_ANTIBODY"],
  },
  {
    experimentCode: "ELISA",
    level: "MIN_REQUIRED",
    displayNameZh: "ELISA 需要显色底物",
    displayNameEn: "ELISA needs substrate",
    matcherType: "TAG_ANY",
    matcherValues: ["ELISA_SUBSTRATE"],
  },
  {
    experimentCode: "ELISA",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充细胞刺激或处理试剂",
    displayNameEn: "Recommended stimulation or treatment reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["CELL_STIMULATION_REAGENT", "SIGNALING_MODULATOR"],
  },
  {
    experimentCode: "FLOW",
    level: "MIN_REQUIRED",
    displayNameZh: "流式需要荧光抗体",
    displayNameEn: "Flow cytometry needs fluorescent antibody",
    matcherType: "TAG_ANY",
    matcherValues: ["FLOW_FLUORESCENT_ANTIBODY"],
  },
  {
    experimentCode: "FLOW",
    level: "MIN_REQUIRED",
    displayNameZh: "流式需要染色缓冲液",
    displayNameEn: "Flow cytometry needs stain buffer",
    matcherType: "TAG_ANY",
    matcherValues: ["FLOW_STAIN_BUFFER"],
  },
  {
    experimentCode: "FLOW",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充活死染",
    displayNameEn: "Recommended viability dye",
    matcherType: "TAG_ANY",
    matcherValues: ["FLOW_VIABILITY_DYE"],
  },
  {
    experimentCode: "FLOW",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充一抗或待检 marker 抗体",
    displayNameEn: "Recommended primary or marker antibody",
    matcherType: "TAG_ANY",
    matcherValues: ["FLOW_PRIMARY_ANTIBODY"],
  },
  {
    experimentCode: "WB",
    directionCode: "AUTOPHAGY",
    level: "MIN_REQUIRED",
    displayNameZh: "自噬 WB 需要 LC3",
    displayNameEn: "Autophagy WB needs LC3",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["LC3"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "AUTOPHAGY",
    level: "MIN_REQUIRED",
    displayNameZh: "自噬 WB 需要 p62",
    displayNameEn: "Autophagy WB needs p62",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["P62"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "MIN_REQUIRED",
    displayNameZh: "分泌性自噬 WB 需要 LC3",
    displayNameEn: "Secretory autophagy WB needs LC3",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["LC3"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "MIN_REQUIRED",
    displayNameZh: "分泌性自噬 WB 需要 p62",
    displayNameEn: "Secretory autophagy WB needs p62",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["P62"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "QPCR",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充自噬相关 LC3 引物",
    displayNameEn: "Recommended autophagy LC3 primer",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["LC3"],
  },
  {
    experimentCode: "QPCR",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充自噬相关 p62 引物",
    displayNameEn: "Recommended autophagy p62 primer",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["P62"],
  },
  {
    experimentCode: "WB",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充转染/基因递送试剂以做自噬干预",
    displayNameEn: "Recommended transfection or gene delivery reagent for autophagy perturbation",
    matcherType: "TAG_ANY",
    matcherValues: ["TRANSFECTION_REAGENT", "GENE_DELIVERY_REAGENT"],
  },
  {
    experimentCode: "QPCR",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充分泌性自噬相关 LC3 引物",
    displayNameEn: "Recommended secretory autophagy LC3 primer",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["LC3"],
  },
  {
    experimentCode: "QPCR",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充分泌性自噬相关 p62 引物",
    displayNameEn: "Recommended secretory autophagy p62 primer",
    matcherType: "PRIMER_TARGET_ANY",
    matcherValues: ["P62"],
  },
  {
    experimentCode: "WB",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充转染/基因递送试剂以做分泌性自噬干预",
    displayNameEn: "Recommended transfection or gene delivery reagent for secretory autophagy perturbation",
    matcherType: "TAG_ANY",
    matcherValues: ["TRANSFECTION_REAGENT", "GENE_DELIVERY_REAGENT"],
  },
  {
    experimentCode: "IF",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充自噬相关抗体（LC3 或 p62）",
    displayNameEn: "Recommended autophagy antibody (LC3 or p62)",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["LC3", "P62"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "IF",
    directionCode: "AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充转染/基因递送试剂以做自噬干预",
    displayNameEn: "Recommended transfection or gene delivery reagent for autophagy perturbation",
    matcherType: "TAG_ANY",
    matcherValues: ["TRANSFECTION_REAGENT", "GENE_DELIVERY_REAGENT"],
  },
  {
    experimentCode: "IF",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充分泌性自噬相关抗体（LC3 或 p62）",
    displayNameEn: "Recommended secretory autophagy antibody (LC3 or p62)",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["LC3", "P62"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "IF",
    directionCode: "SECRETORY_AUTOPHAGY",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充转染/基因递送试剂以做分泌性自噬干预",
    displayNameEn: "Recommended transfection or gene delivery reagent for secretory autophagy perturbation",
    matcherType: "TAG_ANY",
    matcherValues: ["TRANSFECTION_REAGENT", "GENE_DELIVERY_REAGENT"],
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "MIN_REQUIRED",
    displayNameZh: "外泌体 WB 需要至少一个 tetraspanin 标志物",
    displayNameEn: "Exosome WB needs at least one tetraspanin marker",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["CD9", "CD63", "CD81"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "MIN_REQUIRED",
    displayNameZh: "外泌体 WB 需要至少一个内体/胞质相关标志物",
    displayNameEn: "Exosome WB needs at least one endosomal or cytosolic marker",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["TSG101", "ALIX"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充 Calnexin 作为污染排查",
    displayNameEn: "Recommended Calnexin contamination control",
    matcherType: "ANTIBODY_TARGET_ANY",
    matcherValues: ["CALNEXIN"],
    matcherAntibodyRole: "PRIMARY",
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充外泌体分离试剂",
    displayNameEn: "Recommended exosome isolation reagent",
    matcherType: "TAG_ANY",
    matcherValues: ["EXOSOME_ISOLATION_REAGENT"],
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充细胞培养基",
    displayNameEn: "Recommended cell culture medium",
    matcherType: "TAG_ANY",
    matcherValues: ["CELL_CULTURE_MEDIUM"],
  },
  {
    experimentCode: "WB",
    directionCode: "EXOSOME",
    level: "RECOMMENDED",
    displayNameZh: "推荐补充血清添加物",
    displayNameEn: "Recommended serum supplement",
    matcherType: "TAG_ANY",
    matcherValues: ["SERUM_SUPPLEMENT"],
  },
];
